name: Get Associated PRs
author: Austen Stone
description: Get PRs associated with a commit
branding:
  icon: "plus"
  color: "blue"

inputs:
  owner:
    description: The owner of the repository
    required: false
  repository:
    description: The repository name
    required: false
  sha:
    description: The SHA of the commit
    default: ${{ github.event.after || github.sha }}
    required: false
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
outputs:
  prs:
    description: The PRs associated with the commit as a JSON string
    value: ${{ steps.get-associated-prs.outputs.PRS }}
  pr_numbers:
    description: The PR numbers associated with the commit as a JSON string
    value: ${{ steps.get-associated-pr-numbers.outputs.PR_NUMBERS }}

runs:
  using: "composite"
  steps:
  - id: get-associated-prs
    run: echo "PRS=$(gh api /repos/$REPO/commits/$COMMIT/pulls)" >> $GITHUB_OUTPUT
    env:
      GH_TOKEN: ${{ inputs.github-token }}
      REPO: ${{ (inputs.owner && inputs.repository) && format('{0}/{1}', inputs.owner, inputs.repository) || github.repository }}
      COMMIT: '${{ inputs.sha }}'
    shell: bash
  - id: get-associated-pr-numbers
    run: echo 'PR_NUMBERS=$(echo '${{ steps.get-associated-prs.outputs.PRS }}' | jq -c '[.[] | .number]')' >> $GITHUB_OUTPUT
    shell: bash