name: Composite Action
author: Austen Stone
description: A Composite Action
branding:
  icon: "plus"
  color: "blue"

inputs:
  owner:
    description: The owner of the repository
    required: false
  repository:
    description: The repository name
    required: false
  sha:
    description: The SHA of the commit
    default: ${{ github.event.after }}
    required: false
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false

runs:
  using: "composite"
  steps:
  - id: get-associated-prs
    run: echo "GH_LIST_ASSOC_PRS=$(gh api /repos/$REPO/commits/$COMMIT/pulls)" >> $GITHUB_OUTPUT
    env:
      GH_TOKEN: '${{ inputs.github-token }}'
      REPO: '${{ (inputs.owner && inputs.repository) && (inputs.owner + '/' + inputs.repository) || github.repository }}'
      COMMIT: '${{ inputs.sha }}'
    shell: bash
  - run: echo "${{ steps.get-associated-prs.outputs.GH_LIST_ASSOC_PRS }}"
