name: Usage
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run:
    name: Run Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: get-pr
        uses: ./
      - run: echo '${{ fromJson(steps.get-pr.outputs.prs)[0].number }}'
        shell: bash
      - run: echo '${{ fromJson(steps.get-pr.outputs.pr-numbers)[0] }}'
        shell: bash